### ISSUE TITLE
Deleted freezed not removed

### ISSUE THREAD

**Issue by riccardocescon** [nivisi/vscode-dart-build-runner-tools#1] opened 2024-04-02 20:42 UTC
Hi, i was using this extension and found out something weird.
I have an event class that uses freezed for generating classes, and a bloc class.
The event Is a Part Of of the Bloc.
If i have 5 events and then remove One from the event file, and then run the extension Acton: Build File (by selecting the .freezed.dart file already generated) It Will update, but the class that i have remove Is still present inside the freezed file.
If then i run from the cli the command to build all the files with build runner, then It updates and removes the class as expected

**Comment by nivisi** [comment] 2024-04-03 08:30
@riccardocescon are the commands that you run equal? Perhaps the command executed from the terminal is ran the flag `delete-conflicting-outputs`? If so, you can toggle it in your command palette using the `Enable Delete Conflicting Outputs`:

<img width="603" alt="Screenshot 2024-04-03 at 11 30 12 AM" src="https://github.com/nivisi/vscode-dart-build-runner-tools/assets/33932162/a76421c9-0b53-4ac4-863d-7432ca81561d">

**Comment by riccardocescon** [comment] 2024-04-03 08:58
@nivisi the command that i ran was `flutter packages pub run build_runner build`

**Comment by nivisi** [comment] 2024-04-03 13:40
@riccardocescon hmm doesn't seem to happen for me. Could you please fill steps to reproduce the issue? What I'm doing:
1. Create a freezed class
2. Create multiple constructors, generate the part file
3. Remove a constructor from the source class
4. Run code generation on the freezed file

Is this it?

**Comment by riccardocescon** [comment] 2024-04-04 13:54
Yes @nivisi.
those are the steps.
The only part that is missing is that i have the freezed class that is a part of of another file, so 
example_bloc.dart //part 'example_event,dart'
example_event.dart //part of 'example_bloc.dart'
example_bloc.freezed.dart

**Comment by nivisi** [comment] 2024-10-27 09:46
Closing as I am not able to reproduce the issue. Please feel free to comment below with a different example or a video showcase.

**Closed as not planned by nivisi** 2024-10-27 09:46 UTC
